# Generated by Django 3.0.4 on 2020-06-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20200617_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.URLField(),
        ),
    ]
